BOARD_TAG    = nano328

ARDUINO_DIR = /usr/share/arduino
ARDUINO_PORT = /dev/ttyUSB0
MONITOR_PORT = /dev/ttyUSB0

ARDUINO_LIBS = Json OneWire-master Arduino-Temperature-Control-Library-master
USER_LIB_PATH += /home/arttu/Arduino/lib

include /usr/share/arduino/Arduino.mk


