BOARD_TAG    = nano328

ARDUINO_DIR = /usr/share/arduino
ARDUINO_PORT = /dev/ttyUSB3
MONITOR_PORT = /dev/ttyUSB3

ARDUINO_LIBS = Json
USER_LIB_PATH += ./../lib

include /usr/share/arduino/Arduino.mk

